version: '2'
services:
    hackme-app:
        image: hackme
        external_links:
            - hackme-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hackme?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hackme-mysql:
        extends:
            file: mysql.yml
            service: hackme-mysql
